### ISSUE TITLE
Apps stop running after Apr 29 upgrade due to libstdc++ dependency

### ISSUE THREAD

**Issue by ye-luo** [argonne-lcf/AuroraBugTracking#23]
### Point of Contact

Ye Luo

### Reproducer Path

See details

### Status

Open

### Details

A very common error message
```
/opt/aurora/24.180.3/spack/unified/0.8.0/install/gcc_bootstrap/linux-sles15-x86_64/gcc-7.5.0/gcc-12.2.0-5ieouwtcwrrwan33k5itbqrsrom7cjrh/lib64/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib64/libze_loader.so.1)
```

Before the upgrade, there are two libstdc++ library files.
1. OS `/usr/lib64/libstdc++.so.6`
2. spack has `/opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/gcc-12.2.0/gcc-runtime-12.2.0-267awrk/lib/libstdc++.so.6` mostly copied from spack installed gcc 12.2.

Before upgrade, both libraries are from gcc 12.2. Different files but technically the same library version.
After upgrade, the OS libstdc++ went up to gcc 13.2. the libze follows and depends on the OS libstdc++.
For a given app/library built by spack before the upgrade, for example libmpi.so, its enforced RPATH forces it to `/opt/aurora/24.180.3/spack/unified/0.8.0/install/gcc_bootstrap/linux-sles15-x86_64/gcc-7.5.0/gcc-12.2.0-5ieouwtcwrrwan33k5itbqrsrom7cjrh/lib64/libstdc++.so.6` and breaks dependency of `libze.so`
```
ldd /opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/mpich-4.3.0rc3-fzmrfta/lib/libmpi.so 
/opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/oneapi-2024.07.30.002/mpich-4.3.0rc3-fzmrfta/lib/libmpi.so: /opt/aurora/24.180.3/spack/unified/0.8.0/install/gcc_bootstrap/linux-sles15-x86_64/gcc-7.5.0/gcc-12.2.0-5ieouwtcwrrwan33k5itbqrsrom7cjrh/lib64/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib64/libze_loader.so.1)
```

To prevent such libstdc++ breakage due to OS upgrade + spack inflexibility, we can enforce the gcc-runtime spack package to use system libstdc++.  Namely libstdc++ should have a single source of truth.

Simply change `packages.yaml`
```
  gcc-runtime:
    externals:
    - spec: gcc-runtime@12.2.0 %gcc@=12.2.0
      prefix: /opt/aurora/24.180.3/spack/unified/0.8.0/install/linux-sles15-x86_64/gcc-12.2.0/gcc-runtime-12.2.0-267awrk
    buildable: false
```
to
```
  gcc-runtime:
    externals:
    - spec: gcc-runtime@12.2.0 # not sure if %gcc@=12.2.0 is necessary
      prefix: /usr
    buildable: false
```
by doing so, gcc-runtime will be dummy and the OS libstdc++ will be used. Also the path to the spack gcc lib won't be added to RPATH of spack built libraries.

### Is this a priority/blocking bug?

- [ ] Priority
